fix(checkbox): svg size
amblerhq/andive pull request #121
Opened 2021-12-23 10:44 UTC by GuillaumeSarfati

# BEFORE
![Screenshot 2021-12-23 at 11 40 10](https://user-images.githubusercontent.com/19313367/147229163-ee3ec7d6-cbb4-48ab-8c7f-726111b051b4.png)
# AFTER
![Screenshot 2021-12-23 at 11 40 21](https://user-images.githubusercontent.com/19313367/147229195-b822e152-a111-412e-b6b8-bb2ceea36630.png)

2021-12-27 15:41 UTC, GuillaumeSarfati commented
https://app.shortcut.com/ambler/story/6780/nettoyer-l-%C3%A9tape-raison-de-transport-sur-a4h

2021-12-28 11:11 UTC, rhavenz requested changes

2021-12-28 11:11 UTC, rhavenz commented on packages/andive/src/components/checkbox.tsx
> +  align-items: flex-start;
🤷

2021-12-28 11:11 UTC, rhavenz commented on packages/andive/src/components/checkbox.tsx
> +  }
Il faut pas plutot ajouter un min-width sur `SvgIcon` ?

2021-12-28 13:22 UTC, GuillaumeSarfati commented on packages/andive/src/components/checkbox.tsx
> +  align-items: flex-start;
pour aligner vers le haut

2021-12-28 13:24 UTC, GuillaumeSarfati commented on packages/andive/src/components/checkbox.tsx
> +  }
pourquoi ?

2021-12-29 12:27 UTC, rhavenz approved these changes

2021-12-29 12:28 UTC, merged