feat(dropdownMenu): add isOpen and minWidth props
amblerhq/andive pull request #123
Opened 2021-12-29 15:10 UTC by GuillaumeSarfati

2021-12-29 16:31 UTC, GuillaumeSarfati commented
CR @rhavenz  : 
- Changer isOpen -> defaultOpen
- Passer de minWidth a width
- Trouver un nom plus parlant pour la props width

2021-12-29 16:32 UTC, GuillaumeSarfati commented
de

> CR @rhavenz :
> 
> * Changer isOpen -> defaultOpen
> * Passer de minWidth a width
> * Trouver un nom plus parlant pour la props width

defaultDropDownWidth ?

2022-01-03 13:08 UTC, nicobarray requested changes
Ce me semble plus propre que de passer par un prop pour une propriété CSS au composant Dropdown.

2022-01-03 13:08 UTC, nicobarray commented on packages/andive/src/components/dropdown-menu.js
> +  ${({defaultDropDownWidth}) =>
On peut aussi retirer le prop, exposer le className et laisser l'appelant du composant utiliser "styled(Dropdown)` width: whatever; ` et ajouter `width: auto` ici dans le css du Dropdown.

2022-01-03 15:05 UTC, nicobarray approved these changes

2022-01-03 15:05 UTC, merged