feat(card): create card component
amblerhq/andive pull request #15
Opened 2019-10-23 15:20 UTC by lucamerzi

2019-10-23 15:25 UTC, lucamerzi commented
Relates #7

2019-10-23 23:17 UTC, nicobarray requested changes
In the current state of andive, we only want the simplest card component that defines:
- a white background
- the inner padding
- the border style (no shadow)
- the correct border-radius

(For reference, check the ambler4hospital/trips page cards).

Other features, like foldable content, title or inner dividers will be handled by other components (resp. Accordeon, Typography.H1 and Divider)

I'd love to merge this with the simplest specs. If you want to do a bit more, a customizable root element would be awesome, example:

```
const rootCss = css` // define border & spacings `
const CardRoot = styled.div` ${rootCss} `

function Card({ component, children }) {
  // ? Maybe memoize this RootComponent based on prop.component to
  // ? avoid recreating a new styled instance on each render.
  const RootComponent = styled(component)`${rootCss}` || CardRoot
  // ...
  return <RootComponent>
    {children}
  </RootComponent>
}
```

Feel free to inspire yourself from the above example. This would come handy when using react-grid-system's <Col /> and <Row /> components as `<Card component={Col} xs={12} md={6} />`

2019-11-13 14:24 UTC, lucamerzi commented
This PR applies [specs](https://amblerworkspace.slack.com/archives/CHVC3CKN2/p1573650651002300?thread_ts=1573648599.000800&cid=CHVC3CKN2) discussed in the slack channel `product-andive`.

2019-11-13 17:21 UTC, nicobarray requested changes
🙌 Thanks for the work, we are close to merging it 👍 Let's just convert it to typescript (the component, not the story).

2019-11-13 17:21 UTC, nicobarray commented on docs/stories/card.stories.js
> +  'Cards are non-clickable. They group information together and often have an icon that allows the user to perform actions (edit, add items, etc.)'
```suggestion
  'Cards are non-clickable. They group information together and often have buttons that allow the user to perform actions (edit, add items, etc.)'
```

2019-11-13 17:21 UTC, nicobarray commented on packages/andive/.storybook/config.js
> +  require('../src/stories/card.stories')
This should be in docs/.storybook/config.js

2019-11-13 17:21 UTC, nicobarray commented on packages/andive/src/components/card.js
> +  border: 1px solid ${palette.hexToRGBA(palette.lightPrimary)};
```suggestion
  border: 1px solid ${palette.lightPrimary};
```

palette.hexToRGBA is only used to add transparency to the color.

2019-11-13 17:21 UTC, nicobarray commented on packages/andive/src/components/card.js
> +}
I should have said so earlier, but let's make it in typescript (and not use prop-types anymore).

2019-11-14 13:08 UTC, nicobarray approved these changes
🙌 LGTM. Later we'll ask ourselves how to properly type `children` prop.

2019-11-14 13:08 UTC, merged